# Generated by Django 4.1.3 on 2022-12-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_authors_course_price_course_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclass',
            options={'verbose_name': 'course class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelTable(
            name='courseclass',
            table='course_class',
        ),
    ]
